# Generated by Django 3.2.13 on 2022-07-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='apps',
            field=models.ManyToManyField(related_name='apps', to='apps.applists'),
        ),
    ]
