# Generated by Django 3.1.4 on 2022-05-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Btech_percentage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Scale_Btech_percentage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_CTC',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='current_company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='default_coding_lang',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dream_company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='expected_CTC',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='institute_country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='institute_location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='institute_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='languages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notice_period',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='willing_to_relocate',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='workExp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='yearOfPassing',
        ),
    ]
