# Generated by Django 3.2.6 on 2022-07-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('accounts', '0002_profile_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='plans.plan'),
        ),
    ]
