# Generated by Django 3.2.6 on 2022-07-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('accounts', '0006_profile_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='plan',
        ),
        migrations.AddField(
            model_name='profile',
            name='plans',
            field=models.ManyToManyField(to='plans.Plan'),
        ),
    ]
