# Generated by Django 3.2.6 on 2022-07-28 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220728_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notifications')),
                ('body', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('url_name', models.CharField(blank=True, default='View', max_length=255, null=True)),
                ('notified_time', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, max_length=16, null=True, unique=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='accounts.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
