# Generated by Django 3.2.6 on 2022-07-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220728_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='plan_start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
