# Generated by Django 3.2.6 on 2022-07-27 19:10

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.CharField(default=groups.models.generate_code, editable=False, max_length=20),
        ),
    ]
