# Generated by Django 3.1.4 on 2022-05-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applists',
            fields=[
                ('appname', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='App name')),
                ('appimg', models.ImageField(blank=True, null=True, upload_to='app_images')),
                ('lastdate', models.CharField(max_length=50, verbose_name='last updated')),
                ('createddata', models.DateField(blank=True, null=True, verbose_name='created dat')),
            ],
        ),
    ]
