# Generated by Django 3.2.13 on 2022-05-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applists',
            fields=[
                ('appname', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='App name')),
                ('appimg', models.ImageField(blank=True, null=True, upload_to='app_images')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='updated date')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_name', models.CharField(blank=True, max_length=200, null=True)),
                ('utility_short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('utility_state', models.CharField(blank=True, max_length=50, null=True)),
                ('utility_district', models.CharField(blank=True, max_length=50, null=True)),
                ('utility_country', models.CharField(blank=True, max_length=50, null=True)),
                ('utility_postalcode', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=50, null=True)),
                ('contact_phnum', models.CharField(blank=True, max_length=15, null=True)),
                ('contact_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('office_address', models.TextField(blank=True, max_length=200, null=True)),
                ('info_created_at', models.DateTimeField(auto_now_add=True)),
                ('info_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
