# Generated by Django 3.2.13 on 2022-06-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='appname',
            field=models.ManyToManyField(to='apps.applists'),
        ),
    ]
