# Generated by Django 3.2.13 on 2022-05-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(editable=False, max_length=16, null=True, unique=True),
        ),
    ]
