# Generated by Django 3.2.13 on 2022-06-29 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='csvs',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='appname',
        ),
        migrations.DeleteModel(
            name='settings',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
