# Generated by Django 3.2.13 on 2022-05-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_customer_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
        migrations.AddField(
            model_name='applists',
            name='slug',
            field=models.SlugField(editable=False, max_length=16, null=True, unique=True),
        ),
    ]
