# Generated by Django 3.1.4 on 2022-05-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20220510_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applists',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date'),
        ),
        migrations.AlterField(
            model_name='applists',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='updated date'),
        ),
    ]
