# Generated by Django 3.2.13 on 2022-06-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_customer_appname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applists',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='applists',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
