# Generated by Django 3.2.13 on 2022-05-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20220523_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='csvs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.CharField(blank=True, max_length=50, null=True)),
                ('LatM', models.CharField(blank=True, max_length=50, null=True)),
                ('LatS', models.CharField(blank=True, max_length=50, null=True)),
                ('NS', models.CharField(blank=True, max_length=50, null=True)),
                ('LonD', models.CharField(blank=True, max_length=50, null=True)),
                ('LonM', models.CharField(blank=True, max_length=50, null=True)),
                ('LonS', models.CharField(blank=True, max_length=50, null=True)),
                ('EW', models.CharField(blank=True, max_length=50, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='applists',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, null=True, unique=True),
        ),
    ]
