# Generated by Django 3.1.4 on 2022-05-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20220510_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applists',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated date'),
        ),
    ]
