# Generated by Django 3.2.13 on 2022-06-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20220617_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applists',
            old_name='updated_at',
            new_name='date_modified',
        ),
        migrations.RenameField(
            model_name='applists',
            old_name='created_at',
            new_name='date_published',
        ),
    ]
