# Generated by Django 3.1.4 on 2022-05-10 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20220510_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applists',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='applists',
            name='updated_at',
        ),
    ]
