# Generated by Django 3.2.13 on 2022-05-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20220526_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvs',
            old_name='Lat',
            new_name='LatD',
        ),
    ]
