# Generated by Django 3.1.4 on 2022-05-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20220510_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='applists',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created date'),
        ),
        migrations.AddField(
            model_name='applists',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='updated date'),
        ),
    ]
